show DATABASES;

CREATE TABLE `dosen` (
  `kode_dosen` varchar(10) NOT NULL,
  `nama_dosen` varchar(100) DEFAULT NULL
) 
drop table dosen;

INSERT INTO `dosen` (`kode_dosen`, `nama_dosen`) VALUES
('D001', 'Abdul Chalim, SAg., MPd.I'),
('D002', 'Ade Ismail'),
('D003', 'Agung Nugroho Pramudhita ST., MT.'),
('D004', 'Ahmadi Yuli Ananta ST., MM.'),
('D005', 'Ane Fany Novitasari, SH.MKn.'),
('D006', 'Annisa Puspa Kirana MKom.'),
('D007', 'Annisa Taufika Firdausi ST., MT.'),
('D008', 'Anugrah Nur Rahmanto SSn., MDs.'),
('D009', 'Ariadi Retno Ririd SKom., MKom.'),
('D010', 'Arie Rachmad Syulistyo SKom., MKom.'),
('D011', 'Arief Prasetyo SKom., MKom.'),
('D012', 'Arwin Sumari ST., MT., DR.'),
('D013', 'Atiqah Nurul Asri SPd., MPd.'),
('D014', 'Bagas Satya Dian Nugraha, ST., MT.'),
('D015', 'Banni Satria Andoko, S. Kom., M.MSI'),
('D016', 'Budi Harijanto ST., MMKom.'),
('D017', 'Cahya Rahmad ST., MKom. DR.Eng'),
('D018', 'Candra Bella Vista SKom., MT.'),
('D019', 'Candrasena Setiadi ST., MMT.'),
('D020', 'Deasy Sandhya Elya Ikawati SSi., MSi.'),
('D021', 'Deddy Kusbianto PA Ir. MMKom.'),
('D022', 'Dhebys Suryani SKom. MT.'),
('D023', 'Dian Hanifudin Subhi SKom., MT.'),
('D024', 'Dika Rizky Yunianto SKom., MKom.'),
('D025', 'Dimas Wahyu Wibowo ST., MT.'),
('D026', 'Dodit Supriyanto SKom., MT.'),
('D027', 'Dwi Puspitasari SKom., MKom.'),
('D028', 'Eka Larasati Amalia, SST., MT.'),
('D029', 'Ekojono, ST., M.Kom.'),
('D030', 'Elok Nur Hamdana, ST., MT'),
('D031', 'Erfan Rohadi, ST., MEng., PhD.'),
('D032', 'Faiz Ushbah Mubarok, SPd., MPd.'),
('D033', 'Farid Angga Pribadi, SKom.,MKom.'),
('D034', 'Farida Ulfa, SPd., MPd.'),
('D035', 'Gunawan Budi Prasetyo, ST., MMT., Ph.D.'),
('D036', 'Habibie Ed Dien, MT.'),
('D037', 'Hairus'),
('D038', 'Hendra Pradibta, SE., M.Sc.'),
('D039', 'Ika Kusumaning Putri, MT.'),
('D040', 'Imam Fahrur Rozi, ST., MT.'),
('D041', 'Indra Dharma Wijaya, ST., MMT.'),
('D042', 'Irsyad Arif Mashudi, M.Kom'),
('D043', 'Kadek Suarjuna Batubulan, SKom, MT.'),
('D044', 'Luqman Affandi, SKom., MMSI.'),
('D045', 'M. Hasyim Ratsanjani'),
('D046', 'Mamluatul Haniah'),
('D047', 'Meyti Eka Apriyani ST., MT.'),
('D048', 'Milyun Nima Shoumi'),
('D049', 'Moch. Zawaruddin Abdullah, S.ST., M.Kom'),
('D050', 'Moh. Amin'),
('D051', 'Muhammad Afif Hendrawan, S.Kom.'),
('D052', 'Muhammad Shulhan Khairy, SKom., MKom.'),
('D053', 'Muhammad Unggul Pamenang, SSt., MT.'),
('D054', 'Mungki Astiningrum, ST., MKom.'),
('D055', 'Mustika Mentari, SKom., MKom.'),
('D056', 'Noprianto'),
('D057', 'Odhitya Desta Triswidrananta, SPd., MPd.'),
('D058', 'Pramana Yoga Saputra, SKom., MMT.'),
('D059', 'Putra Prima A., ST., MKom.'),
('D060', 'Rakhmat Arianto SST., MKom.'),
('D061', 'Rawansyah., Drs., MPd.'),
('D062', 'Retno Damayanti, SPd.'),
('D063', 'Ridwan Rismanto, SST., MKom.'),
('D064', 'Rizki Putri Ramadhani, S.S., M.Pd.'),
('D065', 'Rizky Ardiansyah, SKom., MT.'),
('D066', 'Robby Anggriawan SE., ME.'),
('D067', 'Rokhimatul Wakhidah SPd. MT.'),
('D068', 'Rosa Andrie Asmara, ST., MT., Dr. Eng.'),
('D069', 'Rudy Ariyanto, ST., MCs.'),
('D070', 'Satrio Binusa S, SS, M.Pd'),
('D071', 'Septian Enggar Sukmana, SPd., MT.'),
('D072', 'Shohib Muslim'),
('D073', 'Siti Romlah, Dra., M.M.'),
('D074', 'Sofyan Noor Arief, S.ST., M.Kom.'),
('D075', 'Ulla Delfiana Rosiani, ST., MT.'),
('D076', 'Usman Nurhasan, S.Kom., MT.'),
('D077', 'Very Sugiarto, SPd., MKom.'),
('D078', 'Vipkas Al Hadid Firdaus, ST.,MT.'),
('D079', 'Vivi Nur Wijayaningrum, S.Kom, M.Kom'),
('D080', 'Vivin Ayu Lestari, SPd.'),
('D081', 'Widaningsih Condrowardhani, SH., MH.'),
('D082', 'Wilda Imama Sabilla, S.Kom., M.Kom.'),
('D083', 'Yoppy Yunhasnawa, SST., MSc.'),
('D084', 'Yuri Ariyanto, SKom., MKom.'),
('D085', 'Zulmy Faqihuddin Putera, S.Pd., M.Pd');

CREATE TABLE `mahasiswa` (
  `kode_mahasiswa` varchar(10) NOT NULL,
  `nama_mahasiswa` varchar(100) DEFAULT NULL,
  `jurusan_mahasiswa` varchar(100) DEFAULT NULL;
) 
drop table mahasiswa;

INSERT INTO `mahasiswa` (`kode_mahasiswa`, `nama_mahasiswa`, `jurusan_mahasiswa`) VALUES
('001', 'Alfahfiza', 'Teknik Informatika'),
('002', 'Arianta', 'Sistem Informasi Bisnis'),
('003', 'Aulia', 'Teknik Informatika'),
('004', 'Ayu', 'Sistem Informasi Bisnis'),
('005', 'Bayu', 'Teknik Informatika'),
('006', 'Candra', 'Sistem Informasi Bisnis'),
('007', 'Dewa', 'Teknik Informatika'),
('008', 'Eka', 'Sistem Informasi Bisnis'),
('009', 'Fadli', 'Teknik Informatika'),
('010', 'Farhan', 'Sistem Informasi Bisnis'),
('011', 'Febri', 'Teknik Informatika'),
('012', 'Fitri', 'Sistem Informasi Bisnis'),
('013', 'Firdaus', 'Teknik Informatika'),
('014', 'Firman', 'Sistem Informasi Bisnis'),
('015', 'Gede', 'Teknik Informatika'),
('016', 'Hana', 'Sistem Informasi Bisnis'),
('017', 'Hardi', 'Teknik Informatika'),
('018', 'Hayati', 'Sistem Informasi Bisnis'),
('019', 'Hesti', 'Teknik Informatika'),
('020', 'Ikhsan', 'Sistem Informasi Bisnis'),
('021', 'Irfan', 'Teknik Informatika'),
('022', 'Jihad', 'Sistem Informasi Bisnis'),
('023', 'Julian', 'Teknik Informatika'),
('024', 'Krisna', 'Sistem Informasi Bisnis'),
('025', 'Kurnia', 'Teknik Informatika'),
('026', 'Laila', 'Sistem Informasi Bisnis'),
('027', 'Laili', 'Teknik Informatika'),
('028', 'M. Fadhil', 'Sistem Informasi Bisnis'),
('029', 'M. Firdaus', 'Teknik Informatika'),
('030', 'M. Nur', 'Sistem Informasi Bisnis'),
('031', 'M. Rizky', 'Teknik Informatika'),
('032', 'M. Syarif', 'Sistem Informasi Bisnis'),
('033', 'Mahdi', 'Teknik Informatika'),
('034', 'Maman', 'Sistem Informasi Bisnis'),
('035', 'Mandiri', 'Teknik Informatika'),
('036', 'Mulyana', 'Sistem Informasi Bisnis'),
('037', 'Nadhira', 'Teknik Informatika'),
('038', 'Nurhayati', 'Sistem Informasi Bisnis'),
('039', 'Nurjannah', 'Teknik Informatika'),
('040', 'Rahma', 'Sistem Informasi Bisnis'),
('041', 'Raihan', 'Teknik Informatika'),
('042', 'Risma', 'Sistem Informasi Bisnis'),
('043', 'Rizqi', 'Teknik Informatika'),
('044', 'Rizky', 'Sistem Informasi Bisnis'),
('045', 'Sabrina', 'Teknik Informatika'),
('046', 'Sahabat', 'Sistem Informasi Bisnis'),
('047', 'Samsul', 'Teknik Informatika'),
('048', 'Sarah', 'Sistem Informasi Bisnis'),
('049', 'Satriya', 'Teknik Informatika'),
('050', 'Siti', 'Sistem Informasi Bisnis'),
('051', 'Sofia', 'Teknik Informatika'),
('052', 'Syukri', 'Sistem Informasi Bisnis'),
('053', 'Teguh', 'Teknik Informatika'),
('054', 'Tiara', 'Sistem Informasi Bisnis'),
('055', 'Umar', 'Teknik Informatika'),
('056', 'Ummi', 'Sistem Informasi Bisnis'),
('057', 'Wahyu', 'Teknik Informatika'),
('058', 'Wilda', 'Sistem Informasi Bisnis'),
('059', 'Wulan', 'Teknik Informatika'),
('060', 'Xaverius', 'Sistem Informasi Bisnis'),
('061', 'Yasir', 'Teknik Informatika'),
('062', 'Yusuf', 'Sistem Informasi Bisnis'),
('063', 'Zahra', 'Teknik Informatika'),
('064', 'Zul', 'Sistem Informasi Bisnis'),
('065', 'Zulka', 'Teknik Informatika'),
('066', 'Zulka', 'Sistem Informasi Bisnis'),
('067', 'Zulka', 'Teknik Informatika'),
('068', 'Zulka', 'Sistem Informasi Bisnis'),
('069', 'Zulka', 'Teknik Informatika'),
('070', 'Zulka', 'Sistem Informasi Bisnis'),
('071', 'Zulka', 'Teknik Informatika'),
('072', 'Zulka', 'Sistem Informasi Bisnis'),
('073', 'Zulka', 'Teknik Informatika'),
('074', 'Zulka', 'Sistem Informasi Bisnis'),
('075', 'Zulka', 'Teknik Informatika'),
('076', 'Zulka', 'Sistem Informasi Bisnis'),
('077', 'Zulka', 'Teknik Informatika'),
('078', 'Zulka', 'Sistem Informasi Bisnis'),
('079', 'Zulka', 'Teknik Informatika'),
('080', 'Zulka', 'Sistem Informasi Bisnis'),
('081', 'Zulka', 'Teknik Informatika'),
('082', 'Zulka', 'Sistem Informasi Bisnis'),
('083', 'Zulka', 'Teknik Informatika'),
('084', 'Zulka', 'Sistem Informasi Bisnis'),
('085', 'Zulka', 'Teknik Informatika'),
('086', 'Zulka', 'Sistem Informasi Bisnis'),
('087', 'Zulka', 'Teknik Informatika'),
('088', 'Zulka', 'Sistem Informasi Bisnis'),
('089', 'Zulka', 'Teknik Informatika'),
('090', 'Zulka', 'Sistem Informasi Bisnis');



CREATE TABLE `admin` (
  `id_admin` int(11) NOT NULL AUTO_INCREMENT,
  `nama_admin` varchar(100) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_admin`)
);

INSERT INTO `admin` (`id_admin`, `nama_admin`, `username`, `password`) VALUES
(1, 'Aris', 'aris', 'aris'),
(2, 'Budi', 'budi', 'budi'),
(3, 'Cahya', 'cahya', 'cahya'),
(4, 'Deni', 'deni', 'deni'),
(5, 'Eko', 'eko', 'eko'),
(6, 'Farid', 'farid', 'farid'),
(7, 'Galih', 'galih', 'galih'),
(8, 'Hanan', 'hanan', 'hanan'),
(9, 'Iqbal', 'iqbal', 'iqbal'),
(10, 'Joko', 'joko', 'joko');




CREATE TABLE `dokumen` (
  `kode_dokumen` varchar(5) NOT NULL,
  `nama_dokumen` varchar(100) DEFAULT NULL
) 


INSERT INTO `dokumen` (`kode_dokumen`, `nama_dokumen`) VALUES
('02001', 'Agama'),
('02002', 'Alajabar Linier'),
('02003', 'Algoritma dan Struktur Data'),
('02004', 'Aljabar Linier'),
('02005', 'Analisis Dan Desan Berorientasi Objek'),
('02006', 'Bahasa Indonesia'),
('02007', 'Bahasa Inggris'),
('02008', 'Bahasa Inggris 2'),
('02009', 'Bahasa Inggris Persiapan Kerja'),
('02010', 'Basis Data'),
('02011', 'Desain Pemrograman Web'),
('02012', 'Digital Entrepreneurship'),
('02013', 'E-Business'),
('02014', 'Etika Profesi Bidang TI'),
('02015', 'Internet Of Things'),
('02016', 'Kewarganegaraan'),
('02017', 'Komputasi Multimedia'),
('02018', 'Machine Learning'),
('02019', 'Manajemen Jaringan Komputer'),
('02020', 'Manajemen Proyek'),
('02021', 'Manajemen Proyek '),
('02022', 'Pemrograman Berbasis Framework'),
('02023', 'Pemrograman Mobile'),
('02024', 'Pemrograman Multimedia'),
('02025', 'Pemrograman Web Lanjut'),
('02026', 'Pengembangan Perangkat Lunak Berbasis Object'),
('02027', 'Pengolahan Citra dan Visi Komputer'),
('02028', 'Penulisan Ilmiah'),
('02029', 'Praktikum Algoritma dan Struktur Data'),
('02030', 'Praktikum Basis Data'),
('02031', 'Praktikum Struktur Data'),
('02032', 'Proyek 1_P1'),
('02033', 'Proyek 1_P2'),
('02034', 'Proyek 2_P2'),
('02035', 'Rekayasa Perangkat Lunak'),
('02036', 'Sistem Informasi'),
('02037', 'Sistem Manajemen Basis Data'),
('02038', 'Sistem Operasi'),
('02039', 'Sistem Pendukung Keputusan'),
('02040', 'Struktur Data'),
('02041', 'Teknologi Data'),
('02042', 'Beasiswa S1'),
('02043', 'Beasiswa S2'),
('02044', 'Beasiswa S3'),
('02045', 'Beasiswa D3'),
('02046', 'Beasiswa D4'),
('02047', 'Kegiatan Mahasiswa'),
('02048', 'Kegiatan Dosen'),
('02049', 'Kegiatan Bersama'),
('02050', 'Surat Tugas');


CREATE table notif
create table kateogri
create table favorite
create table filtering
